// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFCa5oTp8XbPdIrr5NGqe0CHc5dUn335o',
    appId: '1:296448643062:web:7d0c0f010fee83810a41d7',
    messagingSenderId: '296448643062',
    projectId: 'airquality-ad334',
    authDomain: 'airquality-ad334.firebaseapp.com',
    databaseURL: 'https://airquality-ad334-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'airquality-ad334.appspot.com',
    measurementId: 'G-RWM47BHZSR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcDmOkeM9t91eyLvcf0u_JlJY3dn0MZUg',
    appId: '1:296448643062:android:7514d42539a335400a41d7',
    messagingSenderId: '296448643062',
    projectId: 'airquality-ad334',
    databaseURL: 'https://airquality-ad334-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'airquality-ad334.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC16Vwkamc5vK1RTPR6ePsgNzEzoY1bCng',
    appId: '1:296448643062:ios:32f9e1b7a2dacc150a41d7',
    messagingSenderId: '296448643062',
    projectId: 'airquality-ad334',
    databaseURL: 'https://airquality-ad334-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'airquality-ad334.appspot.com',
    iosClientId: '296448643062-ro1m046kt3878vmcu1e4kgpi349bqqf1.apps.googleusercontent.com',
    iosBundleId: 'com.example.myfirstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC16Vwkamc5vK1RTPR6ePsgNzEzoY1bCng',
    appId: '1:296448643062:ios:32f9e1b7a2dacc150a41d7',
    messagingSenderId: '296448643062',
    projectId: 'airquality-ad334',
    databaseURL: 'https://airquality-ad334-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'airquality-ad334.appspot.com',
    iosClientId: '296448643062-ro1m046kt3878vmcu1e4kgpi349bqqf1.apps.googleusercontent.com',
    iosBundleId: 'com.example.myfirstapp',
  );
}
